"""empty message

Revision ID: 373a13cb824d
Revises: 
Create Date: 2025-05-24 23:35:32.497108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '373a13cb824d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacancies')
    op.drop_index('title_index', table_name='resumes')
    op.drop_table('resumes')
    op.drop_table('vacancies_replice')
    op.drop_table('workers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workers',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('workers_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('lastname', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='workers_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('vacancies_replice',
    sa.Column('resume_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vacancy_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cover_letter', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name='vacancies_replice_resume_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], name='vacancies_replice_vacancy_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resume_id', 'vacancy_id', name='vacancies_replice_pkey')
    )
    op.create_table('resumes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('compensation', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('workload', postgresql.ENUM('parttime', 'fulltime', name='workload'), autoincrement=False, nullable=False),
    sa.Column('worker_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.CheckConstraint('compensation > 0', name='check_compens_positive'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name='resumes_worker_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='resumes_pkey')
    )
    op.create_index('title_index', 'resumes', ['title'], unique=False)
    op.create_table('vacancies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('compensation', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='vacancies_pkey')
    )
    # ### end Alembic commands ###
